DROP TABLE IF EXISTS MALHA;
CREATE TABLE MALHA (
  IDMALHA IDENTITY NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  DATAHORAINCLUSAO DATETIME NOT NULL,
  DATAHORAULTIMAATUALIZACAO DATETIME NOT NULL,
  CONSTRAINT PK_IDMALHA PRIMARY KEY (IDMALHA),
  CONSTRAINT UK_NOME UNIQUE (NOME)
);

DROP TABLE IF EXISTS PONTO;
CREATE TABLE PONTO (
  IDPONTO IDENTITY NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  IDMALHA BIGINT NOT NULL,
  CONSTRAINT PK_PONTO PRIMARY KEY (IDPONTO),
  FOREIGN KEY (IDMALHA) REFERENCES MALHA(IDMALHA),
  CONSTRAINT UK_NOME_IDMALHA UNIQUE (NOME, IDMALHA)
);

DROP TABLE IF EXISTS TRECHO;
CREATE TABLE TRECHO (
  IDTRECHO IDENTITY NOT NULL,
  IDPONTOORIGEM BIGINT NOT NULL,
  IDPONTODESTINO BIGINT NOT NULL,
  DISTANCIA DOUBLE NOT NULL,
  CONSTRAINT PK_TRECHO PRIMARY KEY (IDTRECHO),
  FOREIGN KEY (IDPONTOORIGEM) REFERENCES PONTO(IDPONTO),
  FOREIGN KEY (IDPONTODESTINO) REFERENCES PONTO(IDPONTO),
  CONSTRAINT DISTANCIA_UNICA UNIQUE (IDPONTOORIGEM, IDPONTODESTINO)
);
